"""Alert data models for StadiumPulse."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class AlertSeverity(StrEnum):
    """Severity classification for an alert."""

    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(BaseModel):
    """A single alert generated by the AI reasoning engine."""

    alert_id: str = Field(min_length=1, description="Unique alert identifier")
    zone_id: str = Field(min_length=1, description="Zone that triggered this alert")
    zone_name: str = Field(default="", description="Human-readable zone name")
    severity: AlertSeverity
    summary: str = Field(min_length=1, description="One-line plain-English summary")
    reasoning: str = Field(default="", description="Full reasoning chain (XAI)")
    suggested_actions: list[str] = Field(default_factory=list)
    multilingual_alerts: dict[str, str] = Field(
        default_factory=dict,
        description="Dynamic language code → alert text map",
    )
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    is_stale: bool = Field(default=False, description="True if this is a cached/fallback alert")
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    resolved: bool = Field(default=False)
    resolved_at: datetime | None = Field(default=None)


class AlertFilter(BaseModel):
    """Query parameters for filtering the alert feed."""

    severity: AlertSeverity | None = None
    zone_id: str | None = None
    start_time: datetime | None = None
    end_time: datetime | None = None
    page: int = Field(ge=1, default=1)
    page_size: int = Field(ge=1, le=100, default=20)


class AlertFeed(BaseModel):
    """Paginated alert feed response."""

    alerts: list[Alert]
    total_count: int = Field(ge=0)
    page: int = Field(ge=1)
    page_size: int = Field(ge=1)
    has_next: bool = Field(default=False)
